services:
  # Web Service
  - type: web
    name: texas-hill-country
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: chmod +x render-start.sh && ./render-start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hill-country-db
          property: connectionString
      - key: GOOGLE_CALENDAR_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: TINYMCE_API_KEY
        value: vsxa0jsn0xhmac00xmj4sz81e021qjrnz4a23iyvyberhu2q

# Database
databases:
  - name: hill-country-db
    databaseName: hillcountry
    user: hillcountry_user